In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp

### 題目一 : 給定任意兩個 n 維行向量 x, y，n 至少為 4，驗證 x 乘上 y 的 T 次方 的 rank 為 1。

In [10]:
a = np.array([[1],[2],[3],[4]])
b = np.array([[5],[6],[7],[8]])

In [9]:
a*(np.transpose(b))

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

從上可以發現第二列是第一列的6/5，第三列是第一列的7/5，第四列是第一列的8/5，由此可以x乘上y的T次方rank為1。

### 題目二 : (rank 1 分解) 給定任意一個 rank 1 的 n x n 矩陣 A，試著找出兩個 n 維行向量 x, y 使得 A 等於 x 乘 y 的 T 次方

In [13]:
a = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12],[4,8,12,16]])
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

兩個向量x,y皆為四維列向量[1,2,3,4]。

### 題目三 :給一個 4x4 矩陣 A，用增廣矩陣+計算 RREF的方式求出 A 的反矩陣
#### 注意：A 不一定有反矩陣，需觀察增廣矩陣的 RREF 的結果來判斷

In [18]:
a = np.array([[1,2,3,4],[21,4,16,8],[3,6,9,12],[-4,8,-12,16]])
a

array([[  1,   2,   3,   4],
       [ 21,   4,  16,   8],
       [  3,   6,   9,  12],
       [ -4,   8, -12,  16]])

In [19]:
b = np.array([[1,2,3,4,1,0,0,0],
              [21,4,16,8,0,1,0,0],
              [3,6,9,12,0,0,1,0],
              [-4,8,-12,16,0,0,0,1]])
b

array([[  1,   2,   3,   4,   1,   0,   0,   0],
       [ 21,   4,  16,   8,   0,   1,   0,   0],
       [  3,   6,   9,  12,   0,   0,   1,   0],
       [ -4,   8, -12,  16,   0,   0,   0,   1]])

In [20]:
b[1] = b[1]-21*b[0]
b[2] = b[2]-3*b[0]
b[3] = b[3]+4*b[0]

In [21]:
b

array([[  1,   2,   3,   4,   1,   0,   0,   0],
       [  0, -38, -47, -76, -21,   1,   0,   0],
       [  0,   0,   0,   0,  -3,   0,   1,   0],
       [  0,  16,   0,  32,   4,   0,   0,   1]])

看到第三列的[0,0,0,0,-2,0,1,0]，我們可以知道a沒有反矩陣。

用np.linalg.inv()來檢查結果是否正確，a是不是真的沒有反矩陣

In [23]:
np.linalg.inv(a)

LinAlgError: Singular matrix

出現奇異矩陣的錯誤，a確實沒有反矩陣